stages:
  - test
  - build

variables:
  DOCKER_TLS_CERTDIR: "/certs"

build container:
  stage: build
  image: docker:28.5.1-cli
  services:
    - docker:28.5.1-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker info
    - export VERSION=$(sh generate_version.sh)
    - export CONTAINER_TEST_IMAGE="$CI_REGISTRY_IMAGE:$VERSION"
    - 'echo "Using Container Registry: $CI_REGISTRY"'
    - 'echo "Will build and push: $CONTAINER_TEST_IMAGE"'
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE -f Containerfile .
    - docker push $CONTAINER_TEST_IMAGE

unit tests:
  stage: test
  image: python:3.14-slim
  before_script:
    - pip install --no-cache-dir -r requirements.txt
    - pip install --no-cache-dir -r requirements-testing.txt
  script:
    - python -m pytest --cov --cov-report term --cov-report xml:coverage.xml --junitxml=result.xml
  coverage: /TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: result.xml
