stages:
  - test
  - build
  - publish

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

variables:
  TZ: America/New_York
  DOCKER_TLS_CERTDIR: "/certs"
  AST_ENABLE_MR_PIPELINES: true

include:
- template: Jobs/SAST.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml
- template: Jobs/Dependency-Scanning.gitlab-ci.yml

.python_setup: &python_setup
  - apt-get update && apt-get upgrade -y && apt-get install -y locales ca-certificates curl
  - locale-gen en_US.UTF-8
  - export LANG="en_US.UTF-8"
  - export LANGUAGE="en_US.UTF-8"
  - export LC_ALL="en_US.UTF-8"
  - locale
  - apt-get install -y python3 python-is-python3 python3-pip python3-venv

.docker_setup: &docker_setup
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  - |
    tee /etc/apt/sources.list.d/docker.sources <<EOF
    Types: deb
    URIs: https://download.docker.com/linux/ubuntu
    Suites: $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
    Components: stable
    Signed-By: /etc/apt/keyrings/docker.asc
    EOF
  - apt-get update
  - apt list -a docker-ce
  - apt-get install -y docker-ce=5:28.5.1-1~ubuntu.24.04~noble docker-ce-cli=5:28.5.1-1~ubuntu.24.04~noble containerd.io docker-buildx-plugin docker-compose-plugin
  - nohup dockerd >/dev/null 2>&1 &

unit-tests:
  stage: test
  image: python:3.14-slim
  before_script:
    - pip install --no-cache-dir -r requirements.txt
  script:
    - python -m pytest tests/unit --cov --cov-report term --cov-report xml:coverage.xml --junitxml=unit_result.xml
  coverage: /TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: unit_result.xml

integration-tests:
  stage: test
  image: ubuntu:24.04
  services:
    - docker:28.5.1-dind
  before_script:
    - *python_setup
    - *docker_setup
    - python -m venv ci
    - source ci/bin/activate
    - pip install --no-cache-dir -r requirements.txt
  script:
    - python -m pytest tests/integration --junitxml=int_result.xml
  artifacts:
    reports:
      junit: int_result.xml

scan-reporting:
  stage: test
  needs:
    - semgrep-sast
  image: ubuntu:24.04
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
  before_script:
    - *python_setup
    - apt-get install -y python3-jinja2
  script:
    - python pipeline/sast_report.py > comment.json
    - echo "Sending to $CI_SERVER_URL/api/v4/projects/$CI_MERGE_REQUEST_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes"
    - |
      curl --location \
      --request POST \
      "$CI_SERVER_URL/api/v4/projects/$CI_MERGE_REQUEST_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes" \
      --header "PRIVATE-TOKEN: $SCANNER_ACCESS_TOKEN" \
      --header "Content-Type: application/json" \
      --data @comment.json
  
setup-buildenv:
  stage: build
  artifacts:
    reports:
      dotenv: build.env
  script:
    - export VERSION=$(sh generate_version.sh)
    - echo "VERSION=${VERSION}" > build.env && source build.env

build-container:
  stage: build
  image: docker:28.5.1-cli
  services:
    - docker:28.5.1-dind
  needs: 
    - setup-buildenv
  before_script:
    - docker system prune -f
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - export CONTAINER_IMAGE_LATEST="$CI_REGISTRY_IMAGE:latest"
    - export CONTAINER_IMAGE="$CI_REGISTRY_IMAGE:$VERSION"
    - export CONTAINER_IMAGE_REF="$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - 'echo "Using Container Registry: $CI_REGISTRY"'
    - 'echo "Will build and push: $CONTAINER_IMAGE"'
  script:
    - sh generate_version.sh
    - docker build --pull -t $CONTAINER_IMAGE_LATEST -f Containerfile .
    - docker tag $CONTAINER_IMAGE_LATEST "$CONTAINER_IMAGE"
    - docker tag $CONTAINER_IMAGE_LATEST "$CONTAINER_IMAGE_REF"
    - docker push $CONTAINER_IMAGE
    - docker push $CONTAINER_IMAGE_LATEST
    - if [ "$CI_COMMIT_REF_SLUG" = "main" ]; then docker push $CONTAINER_IMAGE_REF; fi

publish-container:
  stage: publish
  image: docker:28.5.1-cli
  services:
    - docker:28.5.1-dind
  needs:
    - setup-buildenv
    - build-container
  rules:
    ## Only tagged commits
    - if: $CI_COMMIT_TAG =~ /^v?[0-9]+[.][0-9]+([.][0-9]+)?$/
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u $DOCKER_HUB_USERNAME --password-stdin
    - export INTERNAL_IMAGE="$CI_REGISTRY_IMAGE:$VERSION"
    - export PUBLIC_IMAGE="veritas1000/forgesteel-warehouse:$VERSION"
    - export PUBLIC_LATEST="veritas1000/forgesteel-warehouse:latest"
    - 'echo "Using Container Registry: $CI_REGISTRY"'
    - 'echo "Will push: $PUBLIC_IMAGE"'
  script:
    - docker pull $INTERNAL_IMAGE
    - docker tag $INTERNAL_IMAGE $PUBLIC_LATEST
    - docker tag $INTERNAL_IMAGE $PUBLIC_IMAGE
    - docker push $PUBLIC_IMAGE
    - docker push $PUBLIC_LATEST
